[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# ✅ Redirect all routes to index.html (React Router fix)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Allow Netlify functions to use extra npm modules
[functions]
  external_node_modules = [
    "firebase-admin",
    "firebase",
    "node-fetch",
    "xlsx"
  ]
  node_bundler = "esbuild"
